In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('https://data.cms.gov/sites/default/files/2023-04/67157de9-d962-4af0-bf0e-3578b3afec58/inpatient.csv', low_memory= False, sep='|')

In [3]:
data

,BENE_ID,CLM_ID,NCH_NEAR_LINE_REC_IDENT_CD,NCH_CLM_TYPE_CD,CLM_FROM_DT,CLM_THRU_DT,NCH_WKLY_PROC_DT,FI_CLM_PROC_DT,CLAIM_QUERY_CODE,PRVDR_NUM,...,PRCDR_DT24,ICD_PRCDR_CD25,PRCDR_DT25,IME_OP_CLM_VAL_AMT,DSH_OP_CLM_VAL_AMT,CLM_UNCOMPD_CARE_PMT_AMT,CLM_LINE_NUM,REV_CNTR,HCPCS_CD,REV_CNTR_DDCTBL_COINSRNC_CD
0,-10000010254618,-10000930037831,V,60,25-Mar-2015,25-Mar-2015,27-Mar-2015,NaN,3,011500,...,NaN,NaN,NaN,0,0,NaN,1,450,99221,NaN
1,-10000010254653,-10000930038030,V,60,24-Sep-2015,24-Sep-2015,25-Sep-2015,NaN,3,017129,...,NaN,NaN,NaN,0,0,NaN,1,450,99221,NaN
2,-10000010254653,-10000930038031,V,60,09-May-2017,10-May-2017,12-May-2017,NaN,3,010052,...,NaN,NaN,NaN,0,0,NaN,1,1,99024,3.0
3,-10000010254656,-10000930038162,V,60,14-Jan-2017,14-Jan-2017,20-Jan-2017,NaN,3,015455,...,NaN,NaN,NaN,0,0,NaN,1,450,73610,3.0
4,-10000010254656,-10000930038162,V,60,14-Jan-2017,14-Jan-2017,20-Jan-2017,NaN,3,015455,...,NaN,NaN,NaN,0,0,NaN,2,450,29515,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58061,-10000010288008,-10000931485965,V,60,08-Jan-2020,14-Jan-2020,17-Jan-2020,NaN,3,050243,...,NaN,NaN,NaN,0,0,NaN,1,1,99221,NaN
58062,-10000010288008,-10000931485967,V,60,23-Oct-2020,23-Oct-2020,30-Oct-2020,NaN,3,056428,...,NaN,NaN,NaN,0,0,NaN,1,450,99221,NaN
58063,-10000010288008,-10000931485969,V,60,22-Aug-2021,23-Aug-2021,27-Aug-2021,NaN,3,056428,...,NaN,NaN,NaN,0,0,NaN,1,450,99221,NaN
58064,-10000010288008,-10000931485971,V,60,13-Sep-2021,16-Sep-2021,17-Sep-2021,NaN,3,050243,...,NaN,NaN,NaN,0,0,NaN,1,1,99221,NaN
58065,-10000010288010,-10000931486024,V,60,11-Jun-2017,11-Jun-2017,16-Jun-2017,NaN,3,555851,...,NaN,NaN,NaN,0,0,NaN,1,450,99221,NaN

In [4]:
print(data.head())

          BENE_ID          CLM_ID NCH_NEAR_LINE_REC_IDENT_CD  NCH_CLM_TYPE_CD  \
0 -10000010254618 -10000930037831                          V               60
1 -10000010254653 -10000930038030                          V               60
2 -10000010254653 -10000930038031                          V               60
3 -10000010254656 -10000930038162                          V               60
4 -10000010254656 -10000930038162                          V               60

   CLM_FROM_DT  CLM_THRU_DT NCH_WKLY_PROC_DT  FI_CLM_PROC_DT  \
0  25-Mar-2015  25-Mar-2015      27-Mar-2015             NaN
1  24-Sep-2015  24-Sep-2015      25-Sep-2015             NaN
2  09-May-2017  10-May-2017      12-May-2017             NaN
3  14-Jan-2017  14-Jan-2017      20-Jan-2017             NaN
4  14-Jan-2017  14-Jan-2017      20-Jan-2017             NaN

   CLAIM_QUERY_CODE PRVDR_NUM  ...  PRCDR_DT24  ICD_PRCDR_CD25  PRCDR_DT25  \
0                 3    011500  ...         NaN             NaN         NaN
1                 3    017129  ...         NaN             NaN         NaN
2                 3    010052  ...         NaN             NaN         NaN
3                 3    015455  ...         NaN             NaN         NaN
4                 3    015455  ...         NaN             NaN         NaN

   IME_OP_CLM_VAL_AMT DSH_OP_CLM_VAL_AMT  CLM_UNCOMPD_CARE_PMT_AMT  \
0                   0                  0                       NaN
1                   0                  0                       NaN
2                   0                  0                       NaN
3                   0                  0                       NaN
4                   0                  0                       NaN

   CLM_LINE_NUM REV_CNTR  HCPCS_CD  REV_CNTR_DDCTBL_COINSRNC_CD
0             1      450     99221                          NaN
1             1      450     99221                          NaN
2             1        1     99024                          3.0
3             1      450     73610                          3.0
4             2      450     29515                          3.0

[5 rows x 197 columns]

In [5]:
drg_codes = data['CLM_DRG_CD']
icd_codes1 = data['ICD_DGNS_CD10']
icd_codes2 = data['ICD_DGNS_CD6']
icd_codes3 = data['ICD_PRCDR_CD4']
icd_codes4 = data['ICD_PRCDR_CD7']
icd_codes5 = data['ICD_PRCDR_CD15']
icd_codes6 = data['ICD_PRCDR_CD25']
hcpcs_codes = data['HCPCS_CD']

In [6]:
drg_frequency = drg_codes.value_counts()
print("DRG Codes Frequency:\n", drg_frequency)
icd_frequency1 = icd_codes1.value_counts()
print("ICD Codes Frequency1:\n", icd_frequency1)
icd_frequency2 = icd_codes2.value_counts()
print("ICD Codes Frequency2:\n", icd_frequency2)
icd_frequency3 = icd_codes3.value_counts()
print("ICD Codes Frequency3:\n", icd_frequency3)
icd_frequency4 = icd_codes4.value_counts()
print("ICD Codes Frequency4:\n", icd_frequency4)
icd_frequency5 = icd_codes5.value_counts()
print("ICD Codes Frequency5:\n", icd_frequency5)
icd_frequency6 = icd_codes6.value_counts()
print("ICD Codes Frequency6:\n", icd_frequency6)
hcpcs_frequency = hcpcs_codes.value_counts()
print("HCPCS Codes Frequency:\n", hcpcs_frequency)

DRG Codes Frequency:
 CLM_DRG_CD
951.0    28831
950.0     1456
949.0     1332
922.0     1110
923.0     1015
         ...
814.0        1
918.0        1
870.0        1
812.0        1
656.0        1
Name: count, Length: 167, dtype: int64
ICD Codes Frequency1:
 ICD_DGNS_CD10
E1121     4461
R931      2149
Z653      2029
E8881     1963
E669      1928
          ...
I25110       1
I25700       1
G43701       1
Z899         1
G249         1
Name: count, Length: 196, dtype: int64
ICD Codes Frequency2:
 ICD_DGNS_CD6
Z653       3230
N1830      3195
E1121      3067
I259       2226
R931       2187
           ...
F02ZFYZ       1
F79           1
I25110        1
R197          1
K117          1
Name: count, Length: 204, dtype: int64
ICD Codes Frequency3:
 ICD_PRCDR_CD4
Z1331      15086
Z9181       4857
Z139        3939
F08H5ZZ     2382
Z9981       2210
F13         1820
F1990       1798
BW03ZZZ     1608
F419         812
07HN33Z      385
Z715         344
F109         327
3E033FZ       29
30277R1       24
6A550Z2       20
N289          14
Z741           8
02RF3KZ        8
02RF4JZ        4
02RF48Z        4
02RF38H        4
02RF37Z        4
02RF0JZ        4
Name: count, dtype: int64
ICD Codes Frequency4:
 ICD_PRCDR_CD7
F1990      4285
Z715       2967
F109       2966
Z9981      2173
Z1331      2005
F08H5ZZ    1657
BW03ZZZ    1148
F13         938
6A550Z2      16
Z8616        14
6A551Z2      12
Name: count, dtype: int64
ICD Codes Frequency5:
 ICD_PRCDR_CD15
Z9981      800
F08H5ZZ    496
F13        176
Z8616       24
0BP13DZ     14
Name: count, dtype: int64
ICD Codes Frequency6:
 ICD_PRCDR_CD25
F08H5ZZ    57
Z9981      25
Name: count, dtype: int64
HCPCS Codes Frequency:
 HCPCS_CD
99221    8298
G0444    7990
96156    5080
99408    4196
99495    3867
         ...
S9361       1
S9355       1
S9374       1
S9377       1
G9829       1
Name: count, Length: 106, dtype: int64

In [9]:
missing_drg = drg_codes.isnull().sum()
print(f"Missing DRG Codes: {missing_drg}")
missing_icd1 = icd_codes1.isnull().sum()
print(f"Missing ICD Codes1: {missing_icd1}")
missing_icd2 = icd_codes2.isnull().sum()
print(f"Missing ICD Codes2: {missing_icd2}")
missing_icd3 = icd_codes1.isnull().sum()
print(f"Missing ICD Codes3: {missing_icd3}")
missing_icd4 = icd_codes4.isnull().sum()
print(f"Missing ICD Codes4: {missing_icd4}")
missing_icd5 = icd_codes5.isnull().sum()
print(f"Missing ICD Codes5: {missing_icd5}")
missing_icd6 = icd_codes6.isnull().sum()
print(f"Missing ICD Codes6: {missing_icd6}")
missing_hcpcs = hcpcs_codes.isnull().sum()
print(f"Missing HCPCS Codes: {missing_hcpcs}")

Missing DRG Codes: 0
Missing ICD Codes1: 0
Missing ICD Codes2: 0
Missing ICD Codes3: 0
Missing ICD Codes4: 0
Missing ICD Codes5: 0
Missing ICD Codes6: 0
Missing HCPCS Codes: 0

In [10]:
data['CLM_DRG_CD'].fillna('MISSING', inplace=True)
print("Top 5 Most Common DRG Codes:\n", drg_frequency.head())
data['ICD_DGNS_CD10'].fillna('MISSING', inplace=True)
print("Top 5 Most Common ICD Codes1:\n", icd_frequency1.head())
data['ICD_DGNS_CD6'].fillna('MISSING', inplace=True)
print("Top 5 Most Common ICD Codes2:\n", icd_frequency2.head())
data['ICD_PRCDR_CD4'].fillna('MISSING', inplace=True)
print("Top 5 Most Common ICD Codes3:\n", icd_frequency3.head())
data['ICD_PRCDR_CD7'].fillna('MISSING', inplace=True)
print("Top 5 Most Common ICD Codes4:\n", icd_frequency4.head())
data['ICD_PRCDR_CD15'].fillna('MISSING', inplace=True)
print("Top 5 Most Common ICD Codes5:\n", icd_frequency5.head())
data['ICD_PRCDR_CD25'].fillna('MISSING', inplace=True)
print("Top 5 Most Common ICD Codes6:\n", icd_frequency6.head())
data['HCPCS_CD'].fillna('MISSING', inplace=True)
print("Top 5 Most Common HCPCS Codes:\n", hcpcs_frequency.head())

Top 5 Most Common DRG Codes:
 CLM_DRG_CD
951.0    28831
950.0     1456
949.0     1332
922.0     1110
923.0     1015
Name: count, dtype: int64
Top 5 Most Common ICD Codes1:
 ICD_DGNS_CD10
E1121    4461
R931     2149
Z653     2029
E8881    1963
E669     1928
Name: count, dtype: int64
Top 5 Most Common ICD Codes2:
 ICD_DGNS_CD6
Z653     3230
N1830    3195
E1121    3067
I259     2226
R931     2187
Name: count, dtype: int64
Top 5 Most Common ICD Codes3:
 ICD_PRCDR_CD4
Z1331      15086
Z9181       4857
Z139        3939
F08H5ZZ     2382
Z9981       2210
Name: count, dtype: int64
Top 5 Most Common ICD Codes4:
 ICD_PRCDR_CD7
F1990    4285
Z715     2967
F109     2966
Z9981    2173
Z1331    2005
Name: count, dtype: int64
Top 5 Most Common ICD Codes5:
 ICD_PRCDR_CD15
Z9981      800
F08H5ZZ    496
F13        176
Z8616       24
0BP13DZ     14
Name: count, dtype: int64
Top 5 Most Common ICD Codes6:
 ICD_PRCDR_CD25
F08H5ZZ    57
Z9981      25
Name: count, dtype: int64
Top 5 Most Common HCPCS Codes:
 HCPCS_CD
99221    8298
G0444    7990
96156    5080
99408    4196
99495    3867
Name: count, dtype: int64